"""Initial migration for assessment system

Revision ID: 0f2cec2e756a
Revises: 
Create Date: 2025-10-11 07:21:38.167275+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2cec2e756a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_item',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('skill_area', sa.JSON(), nullable=False),
    sa.Column('target_proficiency_level', sa.String(length=15), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_item'))
    )
    op.create_table('learning_pathway',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_pathway')),
    sa.UniqueConstraint('name', name=op.f('uq_learning_pathway_name'))
    )
    op.create_table('assessment_config',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('learning_pathway_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('starting_ability', sa.DECIMAL(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=True),
    sa.Column('min_questions', sa.Integer(), nullable=True),
    sa.Column('stopping_criterion', sa.JSON(), nullable=False),
    sa.Column('skill_areas', sa.JSON(), nullable=False),
    sa.Column('proficiency_range', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['learning_pathway_id'], ['learning_pathway.id'], name=op.f('fk_assessment_config_learning_pathway_id_learning_pathway')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_config'))
    )
    op.create_table('course',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('pathway_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('target_proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('primary_skill', sa.String(length=50), nullable=True),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_hours', sa.DECIMAL(), nullable=True),
    sa.Column('difficulty_order', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['pathway_id'], ['learning_pathway.id'], name=op.f('fk_course_pathway_id_learning_pathway')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('assessment_session',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('test_taker_id', sa.String(length=50), nullable=False),
    sa.Column('test_taker_type', sa.Enum('STUDENT', 'TEACHER', name='testtakertype'), nullable=False),
    sa.Column('current_ability', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('standard_error', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['assessment_config.id'], name=op.f('fk_assessment_session_config_id_assessment_config')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_session'))
    )
    op.create_table('lesson',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('lesson_order', sa.Integer(), nullable=True),
    sa.Column('target_skills', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('relative_difficulty', sa.DECIMAL(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_lesson_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_table('assessment_response',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('raw_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('presented_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item.id'], name=op.f('fk_assessment_response_item_id_assessment_item')),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], name=op.f('fk_assessment_response_session_id_assessment_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_response'))
    )
    op.create_table('result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('proficiency_level', sa.String(length=10), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('result_type', sa.Enum('PLACEMENT', 'SPEAKING', 'WRITING', name='resulttype'), nullable=False),
    sa.Column('standard_error', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], name=op.f('fk_result_session_id_assessment_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result'))
    )
    op.create_table('placement_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('final_ability', sa.JSON(), nullable=True),
    sa.Column('completion_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_placement_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_result'))
    )
    op.create_table('recommendation_item',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('content_id', sa.CHAR(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('target_skill', sa.String(length=50), nullable=False),
    sa.Column('skill_gap_size', sa.DECIMAL(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_recommendation_item_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_item'))
    )
    op.create_table('speaking_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_speaking_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_result'))
    )
    op.create_table('writing_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('essay_text', sa.Text(), nullable=True),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_writing_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_result'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_result')
    op.drop_table('speaking_result')
    op.drop_table('recommendation_item')
    op.drop_table('placement_result')
    op.drop_table('result')
    op.drop_table('assessment_response')
    op.drop_table('lesson')
    op.drop_table('assessment_session')
    op.drop_table('course')
    op.drop_table('assessment_config')
    op.drop_table('learning_pathway')
    op.drop_table('assessment_item')
    # ### end Alembic commands ###
